# Generated by Django 4.2.1 on 2023-05-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book_instance',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
    ]
